name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build web to APK
        uses: trulysimple/web-to-apk-action@v1
        with:
          app_name: MyTestApp
          package_name: com.github.testapp
